package main

import (
	"go/ast"
	"io"
	"log"
	"os"
	"os/user"
	"path"
	"strings"
	"text/template"
)

const genmsg = "// Code generated by genapi, which is a API generation tool for Gorgonia. DO NOT EDIT."

const (
	apigenOut = "api_gen.go"
	unOpOut   = "operatorPointwise_unary_gen.go"

	unaryOps  = "operatorPointwise_unary_const.go"
	binaryOps = "operatorPointwise_binary_const.go"
)

var (
	gopath, gorgonialoc, golgiloc string
)

var funcmap = template.FuncMap{
	"lower": strings.ToLower,
}

var (
	unaryTemplate          *template.Template
	binaryTemplate         *template.Template
	broadcastTemplate      *template.Template
	maybeBroadcastTemplate *template.Template
)

const unaryTemplateRaw = ` // {{.FnName}} performs a pointwise {{lower .FnName}}.
func {{.FnName}}(a *Node) (*Node, error) { return unaryOpNode(newElemUnaryOp({{.OpType}}, a), a) }
`

const binaryTemplateRaw = `// {{.FnName}} performs a pointwise {{lower .FnName}} operation.
{{if .AsSame -}}// retSame indicates if the data type of the return value should be the same as the input data type. It defaults to Bool otherwise.
{{end -}}
func {{.FnName}}(a, b *Node{{if .AsSame}}, retSame bool{{end}}) (*Node, error) { {{if not .AsSame -}}return binOpNode(newElemBinOp({{.OpType}}, a, b), a, b) {{else -}}
	op := newElemBinOp({{.OpType}}, a, b)
	op.retSame = retSame
	return binOpNode(op, a, b)
{{end -}}
}
`

const broadcastTemplateRaw = `// Broadcast{{.FnName}} performs a {{lower .FnName}}. The operation is precomposed with a broadcast such that the shapes matches before operations commence.
func Broadcast{{.FnName}}(a, b *Node{{if .AsSame}}, retSame bool{{end}}, leftPattern, rightPattern []byte)(*Node, error) {
	a2, b2, err := Broadcast(a, b, NewBroadcastPattern(leftPattern, rightPattern))
	if err != nil {
		return nil, err
	}
	return {{.FnName}}(a2, b2{{if .AsSame}}, retSame{{end}})
}
`

const maybeBroadcastTemplateRaw = `// Broadcast{{.FnName}} performs a {{lower .FnName}}. The operation is precomposed with a broadcast such that the shapes matches before operations commence.
func Broadcast{{.FnName}}(a, b *G.Node{{if .AsSame}}, retSame bool{{end}}, leftPattern, rightPattern []byte)(*G.Node, error) {
	if a.Shape().Eq(b.Shape()){
		return G.{{.FnName}}(a, b{{if .AsSame}}, retSame{{end}})
	}
	a2, b2, err := G.Broadcast(a, b, G.NewBroadcastPattern(leftPattern, rightPattern))
	if err != nil {
		return nil, err
	}
	return G.{{.FnName}}(a2, b2{{if .AsSame}}, retSame{{end}})
}
`

func init() {
	gopath = os.Getenv("GOPATH")

	if gopath == "" {
		usr, err := user.Current()
		if err != nil {
			log.Fatal(err)
		}
		gopath = path.Join(usr.HomeDir, "go")
		stat, err := os.Stat(gopath)
		if err != nil {
			log.Fatal(err)
		}
		if !stat.IsDir() {
			log.Fatal("You need to define a $GOPATH")
		}
	}
	gorgonialoc = path.Join(gopath, "src/gorgonia.org/gorgonia")
	golgiloc = path.Join(gopath, "src/gorgonia.org/golgi")
	unaryTemplate = template.Must(template.New("Unary").Funcs(funcmap).Parse(unaryTemplateRaw))
	binaryTemplate = template.Must(template.New("Binary").Funcs(funcmap).Parse(binaryTemplateRaw))
	broadcastTemplate = template.Must(template.New("Broadcast").Funcs(funcmap).Parse(broadcastTemplateRaw))
	maybeBroadcastTemplate = template.Must(template.New("MaybeBroadcast").Funcs(funcmap).Parse(maybeBroadcastTemplateRaw))
}

func generateUnary(outFile io.Writer) { _ = "STUB: not implemented"; return }

func generateBinary(outFile io.Writer) { _ = "STUB: not implemented"; return }

func generateBroadcastBinOps(tmpl *template.Template, outFile io.Writer) {
	_ = "STUB: not implemented"
	return
}

func constTypes(decls []ast.Decl, accept, max string) (names []string) {
	_ = "STUB: not implemented"
	return nil
}

func generateAPI() { _ = "STUB: not implemented"; return }

func generateInterfaces() { _ = "STUB: not implemented"; return }

func generateGolgiAPI() { _ = "STUB: not implemented"; return }

func main() {

	generateGolgiAPI()
}
