package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// addOp is the base op for elementwise addition.
type addOp[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op addOp[DT]) String() string { return "+" }

func (op addOp[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, retVal, fo, err := tensor.PrepBasicBinOpCis[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}
	toIncr := fo.Incr
	toBroadcast := fo.Broadcast.BroadcastData()

	adder, ok := e.(tensor.Adder[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, adder, errors.ThisFn())
	}

	switch {
	case toBroadcast:
		err = adder.AddBroadcastable(ctx, a, b, retVal, newAPA, newAPB, toIncr)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = adder.Add(ctx2, a, b, retVal, toIncr)
	}
	return retVal, err
}

// Do performs elementwise addition.
func (op addOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise addition but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op addOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// addVV is a tensor-tensor elementwise addition.
type addVV[DT any] struct {
	addOp[DT]
	binopVV
}

// addVS is a tensor-scalar elementwise addition.
type addVS[DT any] struct {
	addOp[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op addVS[DT]) String() string { return "+·" }

// addSV is a scalar-tensor elementwise addition.
type addSV[DT any] struct {
	addOp[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op addSV[DT]) String() string { return "·+" }
