package stdops

import "gorgonia.org/gorgonia/ops"

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

// Add creates an ops.Op that is correct to the shape of the given operands.
func Add[DT any](a, b ops.Operand) ops.PreallocOp[DT] {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return addVV[DT]{}
	case !aScalar && bScalar:
		return addVS[DT]{}
	case aScalar && !bScalar:
		return addSV[DT]{}
	}
}

// Sub creates an ops.Op that is correct to the shape of the given operands.
func Sub[DT any](a, b ops.Operand) ops.PreallocOp[DT] {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return subVV[DT]{}
	case !aScalar && bScalar:
		return subVS[DT]{}
	case aScalar && !bScalar:
		return subSV[DT]{}
	}
}

// Mul creates an ops.Op that is correct to the shape of the given operands.
func Mul[DT any](a, b ops.Operand) ops.PreallocOp[DT] {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return mulVV[DT]{}
	case !aScalar && bScalar:
		return mulVS[DT]{}
	case aScalar && !bScalar:
		return mulSV[DT]{}
	}
}

// Div creates an ops.Op that is correct to the shape of the given operands.
func Div[DT any](a, b ops.Operand) ops.PreallocOp[DT] {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return divVV[DT]{}
	case !aScalar && bScalar:
		return divVS[DT]{}
	case aScalar && !bScalar:
		return divSV[DT]{}
	}
}

// Pow creates an ops.Op that is correct to the shape of the given operands.
func Pow[DT any](a, b ops.Operand) ops.PreallocOp[DT] {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return powVV[DT]{}
	case !aScalar && bScalar:
		return powVS[DT]{}
	case aScalar && !bScalar:
		return powSV[DT]{}
	}
}

// Mod creates an ops.Op that is correct to the shape of the given operands.
func Mod[DT any](a, b ops.Operand) ops.PreallocOp[DT] {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return modVV[DT]{}
	case !aScalar && bScalar:
		return modVS[DT]{}
	case aScalar && !bScalar:
		return modSV[DT]{}
	}
}

// Lt creates an ops.Op that is correct to the shape of the given operands.
func Lt[DT any, DT2 any](a, b ops.Operand) ops.Desc {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	var z1 DT
	var z2 DT2
	retSame := any(z1) == any(z2)
	if retSame {
		switch {
		default:
			fallthrough
		case !aScalar && !bScalar:
			return ltVVRS[DT]{}
		case !aScalar && bScalar:
			return ltVSRS[DT]{}
		case aScalar && !bScalar:
			return ltSVRS[DT]{}
		}
	}

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return ltVV[DT]{}
	case !aScalar && bScalar:
		return ltVS[DT]{}
	case aScalar && !bScalar:
		return ltSV[DT]{}
	}
}

// Lte creates an ops.Op that is correct to the shape of the given operands.
func Lte[DT any, DT2 any](a, b ops.Operand) ops.Desc {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	var z1 DT
	var z2 DT2
	retSame := any(z1) == any(z2)
	if retSame {
		switch {
		default:
			fallthrough
		case !aScalar && !bScalar:
			return lteVVRS[DT]{}
		case !aScalar && bScalar:
			return lteVSRS[DT]{}
		case aScalar && !bScalar:
			return lteSVRS[DT]{}
		}
	}

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return lteVV[DT]{}
	case !aScalar && bScalar:
		return lteVS[DT]{}
	case aScalar && !bScalar:
		return lteSV[DT]{}
	}
}

// Gt creates an ops.Op that is correct to the shape of the given operands.
func Gt[DT any, DT2 any](a, b ops.Operand) ops.Desc {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	var z1 DT
	var z2 DT2
	retSame := any(z1) == any(z2)
	if retSame {
		switch {
		default:
			fallthrough
		case !aScalar && !bScalar:
			return gtVVRS[DT]{}
		case !aScalar && bScalar:
			return gtVSRS[DT]{}
		case aScalar && !bScalar:
			return gtSVRS[DT]{}
		}
	}

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return gtVV[DT]{}
	case !aScalar && bScalar:
		return gtVS[DT]{}
	case aScalar && !bScalar:
		return gtSV[DT]{}
	}
}

// Gte creates an ops.Op that is correct to the shape of the given operands.
func Gte[DT any, DT2 any](a, b ops.Operand) ops.Desc {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	var z1 DT
	var z2 DT2
	retSame := any(z1) == any(z2)
	if retSame {
		switch {
		default:
			fallthrough
		case !aScalar && !bScalar:
			return gteVVRS[DT]{}
		case !aScalar && bScalar:
			return gteVSRS[DT]{}
		case aScalar && !bScalar:
			return gteSVRS[DT]{}
		}
	}

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return gteVV[DT]{}
	case !aScalar && bScalar:
		return gteVS[DT]{}
	case aScalar && !bScalar:
		return gteSV[DT]{}
	}
}

// ElEq creates an ops.Op that is correct to the shape of the given operands.
func ElEq[DT any, DT2 any](a, b ops.Operand) ops.Desc {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	var z1 DT
	var z2 DT2
	retSame := any(z1) == any(z2)
	if retSame {
		switch {
		default:
			fallthrough
		case !aScalar && !bScalar:
			return elEqVVRS[DT]{}
		case !aScalar && bScalar:
			return elEqVSRS[DT]{}
		case aScalar && !bScalar:
			return elEqSVRS[DT]{}
		}
	}

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return elEqVV[DT]{}
	case !aScalar && bScalar:
		return elEqVS[DT]{}
	case aScalar && !bScalar:
		return elEqSV[DT]{}
	}
}

// ElNe creates an ops.Op that is correct to the shape of the given operands.
func ElNe[DT any, DT2 any](a, b ops.Operand) ops.Desc {
	aScalar := a.Shape().IsScalar()
	bScalar := b.Shape().IsScalar()

	var z1 DT
	var z2 DT2
	retSame := any(z1) == any(z2)
	if retSame {
		switch {
		default:
			fallthrough
		case !aScalar && !bScalar:
			return elNeVVRS[DT]{}
		case !aScalar && bScalar:
			return elNeVSRS[DT]{}
		case aScalar && !bScalar:
			return elNeSVRS[DT]{}
		}
	}

	switch {
	default:
		fallthrough
	case !aScalar && !bScalar:
		return elNeVV[DT]{}
	case !aScalar && bScalar:
		return elNeVS[DT]{}
	case aScalar && !bScalar:
		return elNeSV[DT]{}
	}
}

// Abs creates an ops.Op that performs the named operation.
func Abs[DT any]() ops.PreallocOp[DT] {
	return absOp[DT]{}
}

// Sign creates an ops.Op that performs the named operation.
func Sign[DT any]() ops.PreallocOp[DT] {
	return signOp[DT]{}
}

// Ceil creates an ops.Op that performs the named operation.
func Ceil[DT any]() ops.PreallocOp[DT] {
	return ceilOp[DT]{}
}

// Floor creates an ops.Op that performs the named operation.
func Floor[DT any]() ops.PreallocOp[DT] {
	return floorOp[DT]{}
}

// Sin creates an ops.Op that performs the named operation.
func Sin[DT any]() ops.PreallocOp[DT] {
	return sinOp[DT]{}
}

// Cos creates an ops.Op that performs the named operation.
func Cos[DT any]() ops.PreallocOp[DT] {
	return cosOp[DT]{}
}

// Exp creates an ops.Op that performs the named operation.
func Exp[DT any]() ops.PreallocOp[DT] {
	return expOp[DT]{}
}

// Ln creates an ops.Op that performs the named operation.
func Ln[DT any]() ops.PreallocOp[DT] {
	return lnOp[DT]{}
}

// Log2 creates an ops.Op that performs the named operation.
func Log2[DT any]() ops.PreallocOp[DT] {
	return log2Op[DT]{}
}

// Neg creates an ops.Op that performs the named operation.
func Neg[DT any]() ops.PreallocOp[DT] {
	return negOp[DT]{}
}

// Square creates an ops.Op that performs the named operation.
func Square[DT any]() ops.PreallocOp[DT] {
	return squareOp[DT]{}
}

// Sqrt creates an ops.Op that performs the named operation.
func Sqrt[DT any]() ops.PreallocOp[DT] {
	return sqrtOp[DT]{}
}

// Inv creates an ops.Op that performs the named operation.
func Inv[DT any]() ops.PreallocOp[DT] {
	return invOp[DT]{}
}

// InvSqrt creates an ops.Op that performs the named operation.
func InvSqrt[DT any]() ops.PreallocOp[DT] {
	return invSqrtOp[DT]{}
}

// Log1p creates an ops.Op that performs the named operation.
func Log1p[DT any]() ops.PreallocOp[DT] {
	return log1pOp[DT]{}
}

// Expm1 creates an ops.Op that performs the named operation.
func Expm1[DT any]() ops.PreallocOp[DT] {
	return expm1Op[DT]{}
}

// Cube creates an ops.Op that performs the named operation.
func Cube[DT any]() ops.PreallocOp[DT] {
	return cubeOp[DT]{}
}

// Tanh creates an ops.Op that performs the named operation.
func Tanh[DT any]() ops.PreallocOp[DT] {
	return tanhOp[DT]{}
}
