package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// cube is a elementwise cube.
type cubeOp[DT any] struct{ unop }

// String implements fmt.Stringer.
func (op cubeOp[DT]) String() string { return "³" }

// Do performs elementwise cube.
func (op cubeOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var cuber Cuber[DT]
	var ok bool
	if cuber, ok = e.(Cuber[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, cuber, errors.ThisFn())
	}
	if retVal, _, err = handleFuncOpts[DT](e, a, a.Shape()); err != nil {
		return retVal, errors.Wrapf(err, errors.FailedFuncOpt, errors.ThisFn())
	}
	if err = cuber.Cube(ctx2, a, retVal); err != nil {
		return retVal, err
	}
	// retVal, err = tensor.Cube(a, tensor.WithContext(ctx2))
	task.End()
	return retVal, err
}

// PreallocDo performs elementwise cube but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op cubeOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var cuber Cuber[DT]
	var ok bool
	if cuber, ok = e.(Cuber[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, cuber, errors.ThisFn())
	}
	// TODO check that prealloc has the same shape as expected reetVal shape
	if err = cuber.Cube(ctx2, a, prealloc); err != nil {
		return retVal, err
	}
	task.End()
	return prealloc, err
}

// DiffWRT returns {true} for cube
func (op cubeOp[DT]) DiffWRT(inputs int) []bool { return onetrue }
