package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	"gorgonia.org/dtype"
	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/tensor"
)

// elEqOp is the base op for elementwise equal-to.
type elEqOp[DT any] struct{ binop }

type elEqOpRS[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op elEqOp[DT]) String() string { return "=" }

// String implements fmt.Stringer.
func (op elEqOpRS[DT]) String() string { return "=" }

func (op elEqOp[DT]) do(ctx context.Context, a, b tensor.Basic[DT], prealloc tensor.Basic[bool]) (retVal tensor.Basic[bool], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}
	var ok bool
	if retVal, ok = ret.(tensor.Basic[bool]); !ok {
		return nil, errors.Errorf("Expected %T. Got %v of %T instead", retVal, ret)
	}

	asSame := fo.AsType == a.Dtype()
	toBroadcast := fo.Broadcast.BroadcastData()

	comparer, ok := e.(tensor.Comparer[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, comparer, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for elEq")
	}
	switch {
	case toBroadcast:
		err = comparer.ElEqBroadcastable(ctx, a, b, ret, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = comparer.ElEq(ctx2, a, b, ret, asSame)
	}
	return retVal, err
}

func (op elEqOpRS[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc), tensor.As(dtype.Datatype[DT]{}))
	if err != nil {
		return retVal, err
	}
	var ok bool
	if retVal, ok = ret.(tensor.Basic[DT]); !ok {
		return nil, errors.Errorf("Expected %T. Got %v of %T instead", retVal, ret)
	}

	toBroadcast := fo.Broadcast.BroadcastData()

	comparer, ok := e.(tensor.Comparer[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, comparer, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for elEq")
	}
	switch {
	case toBroadcast:
		err = comparer.ElEqBroadcastable(ctx, a, b, ret, true, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = comparer.ElEq(ctx2, a, b, ret, true)
	}
	return retVal, err
}

// Do performs elementwise equal-to.
func (op elEqOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// Do performs elementwise equal-to.
func (op elEqOpRS[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise equal-to but with a preallocated return value.
// PreallocDo allows elEq to implement ops.PreallocOp.
func (op elEqOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[bool], vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// PreallocDo performs elementwise equal-to but with a preallocated return value.
// PreallocDo allows elEq to implement ops.PreallocOp.
func (op elEqOpRS[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}                                               // DiffWRT returns {false, false} for elEq
func (op elEqOp[DT]) DiffWRT(inputs int) []bool { return twofalses }

// DiffWRT returns {false, false} for elEq
func (op elEqOpRS[DT]) DiffWRT(inputs int) []bool { return twofalses }

// elEqVV is a tensor-tensor elementwise equal-to.
type elEqVV[DT any] struct {
	elEqOp[DT]
	binopVV
}

type elEqVVRS[DT any] struct {
	elEqOpRS[DT]
	binopVV
}

// Type returns the type: (·) (·) :  a → a → b
func (op elEqVV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a) or a
	b := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, a, b)
}

// Type returns the type: (·) :  a → a → a
func (op elEqVVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	return types.NewFunc(a, a, a)
}

// elEqVS is a tensor-scalar elementwise equal-to.
type elEqVS[DT any] struct {
	elEqOp[DT]
	binopVS
}

// elEqVSRS is a tensor-scalar elementwise equal-to.
type elEqVSRS[DT any] struct {
	elEqOpRS[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op elEqVS[DT]) String() string { return "=·" }

// String implements fmt.Stringer.
func (op elEqVSRS[DT]) String() string { return "=·" }

// Type returns the type: (·) :  a → b → c
func (op elEqVS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a)
	b := hm.TypeVariable('b')               // a
	c := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → a
func (op elEqVSRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	b := hm.TypeVariable('b') // b
	return types.NewFunc(a, b, a)
}

// elEqSV is a scalar-tensor elementwise equal-to.
type elEqSV[DT any] struct {
	elEqOp[DT]
	binopSV
}

// elEqSV is a scalar-tensor elementwise equal-to.
type elEqSVRS[DT any] struct {
	elEqOpRS[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op elEqSV[DT]) String() string { return "·=" }

// String implements fmt.Stringer.
func (op elEqSVRS[DT]) String() string { return "·=" }

// Type returns the type: (·) :  a → b → c
func (op elEqSV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // U
	b := hm.TypeVariable('b')               // (T U) or U
	c := types.MakeDependent(b, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → b
func (op elEqSVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // a
	b := hm.TypeVariable('b') // (T b) or b
	return types.NewFunc(a, b, b)
}
