package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	"gorgonia.org/dtype"
	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/tensor"
)

// elNeOp is the base op for elementwise not-equal-to.
type elNeOp[DT any] struct{ binop }

type elNeOpRS[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op elNeOp[DT]) String() string { return "≠" }

// String implements fmt.Stringer.
func (op elNeOpRS[DT]) String() string { return "≠" }

func (op elNeOp[DT]) do(ctx context.Context, a, b tensor.Basic[DT], prealloc tensor.Basic[bool]) (retVal tensor.Basic[bool], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}
	var ok bool
	if retVal, ok = ret.(tensor.Basic[bool]); !ok {
		return nil, errors.Errorf("Expected %T. Got %v of %T instead", retVal, ret)
	}

	asSame := fo.AsType == a.Dtype()
	toBroadcast := fo.Broadcast.BroadcastData()

	comparer, ok := e.(tensor.Comparer[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, comparer, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for elNe")
	}
	switch {
	case toBroadcast:
		err = comparer.ElNeBroadcastable(ctx, a, b, ret, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = comparer.ElNe(ctx2, a, b, ret, asSame)
	}
	return retVal, err
}

func (op elNeOpRS[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc), tensor.As(dtype.Datatype[DT]{}))
	if err != nil {
		return retVal, err
	}
	var ok bool
	if retVal, ok = ret.(tensor.Basic[DT]); !ok {
		return nil, errors.Errorf("Expected %T. Got %v of %T instead", retVal, ret)
	}

	toBroadcast := fo.Broadcast.BroadcastData()

	comparer, ok := e.(tensor.Comparer[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, comparer, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for elNe")
	}
	switch {
	case toBroadcast:
		err = comparer.ElNeBroadcastable(ctx, a, b, ret, true, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = comparer.ElNe(ctx2, a, b, ret, true)
	}
	return retVal, err
}

// Do performs elementwise not-equal-to.
func (op elNeOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// Do performs elementwise not-equal-to.
func (op elNeOpRS[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise not-equal-to but with a preallocated return value.
// PreallocDo allows elNe to implement ops.PreallocOp.
func (op elNeOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[bool], vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// PreallocDo performs elementwise not-equal-to but with a preallocated return value.
// PreallocDo allows elNe to implement ops.PreallocOp.
func (op elNeOpRS[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}                                               // DiffWRT returns {false, false} for elNe
func (op elNeOp[DT]) DiffWRT(inputs int) []bool { return twofalses }

// DiffWRT returns {false, false} for elNe
func (op elNeOpRS[DT]) DiffWRT(inputs int) []bool { return twofalses }

// elNeVV is a tensor-tensor elementwise not-equal-to.
type elNeVV[DT any] struct {
	elNeOp[DT]
	binopVV
}

type elNeVVRS[DT any] struct {
	elNeOpRS[DT]
	binopVV
}

// Type returns the type: (·) (·) :  a → a → b
func (op elNeVV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a) or a
	b := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, a, b)
}

// Type returns the type: (·) :  a → a → a
func (op elNeVVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	return types.NewFunc(a, a, a)
}

// elNeVS is a tensor-scalar elementwise not-equal-to.
type elNeVS[DT any] struct {
	elNeOp[DT]
	binopVS
}

// elNeVSRS is a tensor-scalar elementwise not-equal-to.
type elNeVSRS[DT any] struct {
	elNeOpRS[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op elNeVS[DT]) String() string { return "≠·" }

// String implements fmt.Stringer.
func (op elNeVSRS[DT]) String() string { return "≠·" }

// Type returns the type: (·) :  a → b → c
func (op elNeVS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a)
	b := hm.TypeVariable('b')               // a
	c := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → a
func (op elNeVSRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	b := hm.TypeVariable('b') // b
	return types.NewFunc(a, b, a)
}

// elNeSV is a scalar-tensor elementwise not-equal-to.
type elNeSV[DT any] struct {
	elNeOp[DT]
	binopSV
}

// elNeSV is a scalar-tensor elementwise not-equal-to.
type elNeSVRS[DT any] struct {
	elNeOpRS[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op elNeSV[DT]) String() string { return "·≠" }

// String implements fmt.Stringer.
func (op elNeSVRS[DT]) String() string { return "·≠" }

// Type returns the type: (·) :  a → b → c
func (op elNeSV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // U
	b := hm.TypeVariable('b')               // (T U) or U
	c := types.MakeDependent(b, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → b
func (op elNeSVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // a
	b := hm.TypeVariable('b') // (T b) or b
	return types.NewFunc(a, b, b)
}
