package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// expm1 is a elementwise expm1.
type expm1Op[DT any] struct{ unop }

// String implements fmt.Stringer.
func (op expm1Op[DT]) String() string { return "Expm1" }

// Do performs elementwise expm1.
func (op expm1Op[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var exploger ExpLoger[DT]
	var ok bool
	if exploger, ok = e.(ExpLoger[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, exploger, errors.ThisFn())
	}
	if retVal, _, err = handleFuncOpts[DT](e, a, a.Shape()); err != nil {
		return retVal, errors.Wrapf(err, errors.FailedFuncOpt, errors.ThisFn())
	}
	if err = exploger.Expm1(ctx2, a, retVal); err != nil {
		return retVal, err
	}
	// retVal, err = tensor.Expm1(a, tensor.WithContext(ctx2))
	task.End()
	return retVal, err
}

// PreallocDo performs elementwise expm1 but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op expm1Op[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var exploger ExpLoger[DT]
	var ok bool
	if exploger, ok = e.(ExpLoger[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, exploger, errors.ThisFn())
	}
	// TODO check that prealloc has the same shape as expected reetVal shape
	if err = exploger.Expm1(ctx2, a, prealloc); err != nil {
		return retVal, err
	}
	task.End()
	return prealloc, err
}

// DiffWRT returns {true} for expm1
func (op expm1Op[DT]) DiffWRT(inputs int) []bool { return onetrue }
