package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	"gorgonia.org/dtype"
	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/tensor"
)

// gtOp is the base op for elementwise greater-than.
type gtOp[DT any] struct{ binop }

type gtOpRS[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op gtOp[DT]) String() string { return ">" }

// String implements fmt.Stringer.
func (op gtOpRS[DT]) String() string { return ">" }

func (op gtOp[DT]) do(ctx context.Context, a, b tensor.Basic[DT], prealloc tensor.Basic[bool]) (retVal tensor.Basic[bool], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}

	asSame := fo.AsType == a.Dtype()
	toBroadcast := fo.Broadcast.BroadcastData()

	fullord, ok := e.(tensor.FullOrd[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, fullord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for gt")
	}
	switch {
	case toBroadcast:
		err = fullord.GtBroadcastable(ctx, a, b, ret, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = fullord.Gt(ctx2, a, b, ret, asSame)
	}
	return retVal, err
}

func (op gtOpRS[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc), tensor.As(dtype.Datatype[DT]{}))
	if err != nil {
		return retVal, err
	}

	toBroadcast := fo.Broadcast.BroadcastData()

	fullord, ok := e.(tensor.FullOrd[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, fullord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for gt")
	}
	switch {
	case toBroadcast:
		err = fullord.GtBroadcastable(ctx, a, b, ret, true, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = fullord.Gt(ctx2, a, b, ret, true)
	}
	return retVal, err
}

// Do performs elementwise greater-than.
func (op gtOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// Do performs elementwise greater-than.
func (op gtOpRS[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise greater-than but with a preallocated return value.
// PreallocDo allows gt to implement ops.PreallocOp.
func (op gtOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[bool], vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// PreallocDo performs elementwise greater-than but with a preallocated return value.
// PreallocDo allows gt to implement ops.PreallocOp.
func (op gtOpRS[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}                                             // DiffWRT returns {false, false} for gt
func (op gtOp[DT]) DiffWRT(inputs int) []bool { return twofalses }

// DiffWRT returns {false, false} for gt
func (op gtOpRS[DT]) DiffWRT(inputs int) []bool { return twofalses }

// gtVV is a tensor-tensor elementwise greater-than.
type gtVV[DT any] struct {
	gtOp[DT]
	binopVV
}

type gtVVRS[DT any] struct {
	gtOpRS[DT]
	binopVV
}

// Type returns the type: (·) (·) :  a → a → b
func (op gtVV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a) or a
	b := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, a, b)
}

// Type returns the type: (·) :  a → a → a
func (op gtVVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	return types.NewFunc(a, a, a)
}

// gtVS is a tensor-scalar elementwise greater-than.
type gtVS[DT any] struct {
	gtOp[DT]
	binopVS
}

// gtVSRS is a tensor-scalar elementwise greater-than.
type gtVSRS[DT any] struct {
	gtOpRS[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op gtVS[DT]) String() string { return ">·" }

// String implements fmt.Stringer.
func (op gtVSRS[DT]) String() string { return ">·" }

// Type returns the type: (·) :  a → b → c
func (op gtVS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a)
	b := hm.TypeVariable('b')               // a
	c := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → a
func (op gtVSRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	b := hm.TypeVariable('b') // b
	return types.NewFunc(a, b, a)
}

// gtSV is a scalar-tensor elementwise greater-than.
type gtSV[DT any] struct {
	gtOp[DT]
	binopSV
}

// gtSV is a scalar-tensor elementwise greater-than.
type gtSVRS[DT any] struct {
	gtOpRS[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op gtSV[DT]) String() string { return "·>" }

// String implements fmt.Stringer.
func (op gtSVRS[DT]) String() string { return "·>" }

// Type returns the type: (·) :  a → b → c
func (op gtSV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // U
	b := hm.TypeVariable('b')               // (T U) or U
	c := types.MakeDependent(b, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → b
func (op gtSVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // a
	b := hm.TypeVariable('b') // (T b) or b
	return types.NewFunc(a, b, b)
}
