package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	"gorgonia.org/dtype"
	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/tensor"
)

// gteOp is the base op for elementwise greater-than-or-equal-to.
type gteOp[DT any] struct{ binop }

type gteOpRS[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op gteOp[DT]) String() string { return "≥" }

// String implements fmt.Stringer.
func (op gteOpRS[DT]) String() string { return "≥" }

func (op gteOp[DT]) do(ctx context.Context, a, b tensor.Basic[DT], prealloc tensor.Basic[bool]) (retVal tensor.Basic[bool], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}
	var ok bool
	if retVal, ok = ret.(tensor.Basic[bool]); !ok {
		return nil, errors.Errorf("Expected %T. Got %v of %T instead", retVal, ret)
	}

	asSame := fo.AsType == a.Dtype()
	toBroadcast := fo.Broadcast.BroadcastData()

	fullord, ok := e.(tensor.FullOrd[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, fullord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for gte")
	}
	switch {
	case toBroadcast:
		err = fullord.GteBroadcastable(ctx, a, b, ret, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = fullord.Gte(ctx2, a, b, ret, asSame)
	}
	return retVal, err
}

func (op gteOpRS[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc), tensor.As(dtype.Datatype[DT]{}))
	if err != nil {
		return retVal, err
	}
	var ok bool
	if retVal, ok = ret.(tensor.Basic[DT]); !ok {
		return nil, errors.Errorf("Expected %T. Got %v of %T instead", retVal, ret)
	}

	toBroadcast := fo.Broadcast.BroadcastData()

	fullord, ok := e.(tensor.FullOrd[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, fullord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for gte")
	}
	switch {
	case toBroadcast:
		err = fullord.GteBroadcastable(ctx, a, b, ret, true, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = fullord.Gte(ctx2, a, b, ret, true)
	}
	return retVal, err
}

// Do performs elementwise greater-than-or-equal-to.
func (op gteOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// Do performs elementwise greater-than-or-equal-to.
func (op gteOpRS[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise greater-than-or-equal-to but with a preallocated return value.
// PreallocDo allows gte to implement ops.PreallocOp.
func (op gteOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[bool], vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// PreallocDo performs elementwise greater-than-or-equal-to but with a preallocated return value.
// PreallocDo allows gte to implement ops.PreallocOp.
func (op gteOpRS[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}                                              // DiffWRT returns {false, false} for gte
func (op gteOp[DT]) DiffWRT(inputs int) []bool { return twofalses }

// DiffWRT returns {false, false} for gte
func (op gteOpRS[DT]) DiffWRT(inputs int) []bool { return twofalses }

// gteVV is a tensor-tensor elementwise greater-than-or-equal-to.
type gteVV[DT any] struct {
	gteOp[DT]
	binopVV
}

type gteVVRS[DT any] struct {
	gteOpRS[DT]
	binopVV
}

// Type returns the type: (·) (·) :  a → a → b
func (op gteVV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a) or a
	b := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, a, b)
}

// Type returns the type: (·) :  a → a → a
func (op gteVVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	return types.NewFunc(a, a, a)
}

// gteVS is a tensor-scalar elementwise greater-than-or-equal-to.
type gteVS[DT any] struct {
	gteOp[DT]
	binopVS
}

// gteVSRS is a tensor-scalar elementwise greater-than-or-equal-to.
type gteVSRS[DT any] struct {
	gteOpRS[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op gteVS[DT]) String() string { return "≥·" }

// String implements fmt.Stringer.
func (op gteVSRS[DT]) String() string { return "≥·" }

// Type returns the type: (·) :  a → b → c
func (op gteVS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a)
	b := hm.TypeVariable('b')               // a
	c := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → a
func (op gteVSRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	b := hm.TypeVariable('b') // b
	return types.NewFunc(a, b, a)
}

// gteSV is a scalar-tensor elementwise greater-than-or-equal-to.
type gteSV[DT any] struct {
	gteOp[DT]
	binopSV
}

// gteSV is a scalar-tensor elementwise greater-than-or-equal-to.
type gteSVRS[DT any] struct {
	gteOpRS[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op gteSV[DT]) String() string { return "·≥" }

// String implements fmt.Stringer.
func (op gteSVRS[DT]) String() string { return "·≥" }

// Type returns the type: (·) :  a → b → c
func (op gteSV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // U
	b := hm.TypeVariable('b')               // (T U) or U
	c := types.MakeDependent(b, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → b
func (op gteSVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // a
	b := hm.TypeVariable('b') // (T b) or b
	return types.NewFunc(a, b, b)
}
