package stdops

import (
	"context"

	"gorgonia.org/tensor"
)

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

type Abser[DT any] interface {
	Abs(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type Cuber[DT any] interface {
	Cube(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type ExpLoger[DT any] interface {
	Exp(ctx context.Context, a, retVal tensor.Basic[DT]) error
	Log(ctx context.Context, a, retVal tensor.Basic[DT]) error
	Log2(ctx context.Context, a, retVal tensor.Basic[DT]) error
	Neg(ctx context.Context, a, retVal tensor.Basic[DT]) error
	Log1p(ctx context.Context, a, retVal tensor.Basic[DT]) error
	Expm1(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type IntRepr[DT any] interface {
	Ceil(ctx context.Context, a, retVal tensor.Basic[DT]) error
	Floor(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type InvSqrter[DT any] interface {
	InvSqrt(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type Inver[DT any] interface {
	Inv(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type Signer[DT any] interface {
	Sign(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type Squarer[DT any] interface {
	Square(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type Squarter[DT any] interface {
	Sqrt(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type Tanher[DT any] interface {
	Tanh(ctx context.Context, a, retVal tensor.Basic[DT]) error
}

type Trig[DT any] interface {
	Sin(ctx context.Context, a, retVal tensor.Basic[DT]) error
	Cos(ctx context.Context, a, retVal tensor.Basic[DT]) error
}
