package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// invSqrt is a elementwise 1/√x.
type invSqrtOp[DT any] struct{ unop }

// String implements fmt.Stringer.
func (op invSqrtOp[DT]) String() string { return "1/√·" }

// Do performs elementwise 1/√x.
func (op invSqrtOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var invsqrter InvSqrter[DT]
	var ok bool
	if invsqrter, ok = e.(InvSqrter[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, invsqrter, errors.ThisFn())
	}
	if retVal, _, err = handleFuncOpts[DT](e, a, a.Shape()); err != nil {
		return retVal, errors.Wrapf(err, errors.FailedFuncOpt, errors.ThisFn())
	}
	if err = invsqrter.InvSqrt(ctx2, a, retVal); err != nil {
		return retVal, err
	}
	// retVal, err = tensor.InvSqrt(a, tensor.WithContext(ctx2))
	task.End()
	return retVal, err
}

// PreallocDo performs elementwise 1/√x but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op invSqrtOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var invsqrter InvSqrter[DT]
	var ok bool
	if invsqrter, ok = e.(InvSqrter[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, invsqrter, errors.ThisFn())
	}
	// TODO check that prealloc has the same shape as expected reetVal shape
	if err = invsqrter.InvSqrt(ctx2, a, prealloc); err != nil {
		return retVal, err
	}
	task.End()
	return prealloc, err
}

// DiffWRT returns {true} for invSqrt
func (op invSqrtOp[DT]) DiffWRT(inputs int) []bool { return onetrue }
