package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	"gorgonia.org/dtype"
	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/tensor"
)

// ltOp is the base op for elementwise less-than.
type ltOp[DT any] struct{ binop }

type ltOpRS[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op ltOp[DT]) String() string { return "<" }

// String implements fmt.Stringer.
func (op ltOpRS[DT]) String() string { return "<" }

func (op ltOp[DT]) do(ctx context.Context, a, b tensor.Basic[DT], prealloc tensor.Basic[bool]) (retVal tensor.Basic[bool], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}

	asSame := fo.AsType == a.Dtype()
	toBroadcast := fo.Broadcast.BroadcastData()

	ord, ok := e.(tensor.Ord[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, ord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for lt")
	}
	switch {
	case toBroadcast:
		err = ord.LtBroadcastable(ctx, a, b, ret, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = ord.Lt(ctx2, a, b, ret, asSame)
	}
	return retVal, err
}

func (op ltOpRS[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc), tensor.As(dtype.Datatype[DT]{}))
	if err != nil {
		return retVal, err
	}

	toBroadcast := fo.Broadcast.BroadcastData()

	ord, ok := e.(tensor.Ord[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, ord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for lt")
	}
	switch {
	case toBroadcast:
		err = ord.LtBroadcastable(ctx, a, b, ret, true, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = ord.Lt(ctx2, a, b, ret, true)
	}
	return retVal, err
}

// Do performs elementwise less-than.
func (op ltOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// Do performs elementwise less-than.
func (op ltOpRS[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise less-than but with a preallocated return value.
// PreallocDo allows lt to implement ops.PreallocOp.
func (op ltOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[bool], vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// PreallocDo performs elementwise less-than but with a preallocated return value.
// PreallocDo allows lt to implement ops.PreallocOp.
func (op ltOpRS[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}                                             // DiffWRT returns {false, false} for lt
func (op ltOp[DT]) DiffWRT(inputs int) []bool { return twofalses }

// DiffWRT returns {false, false} for lt
func (op ltOpRS[DT]) DiffWRT(inputs int) []bool { return twofalses }

// ltVV is a tensor-tensor elementwise less-than.
type ltVV[DT any] struct {
	ltOp[DT]
	binopVV
}

type ltVVRS[DT any] struct {
	ltOpRS[DT]
	binopVV
}

// Type returns the type: (·) (·) :  a → a → b
func (op ltVV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a) or a
	b := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, a, b)
}

// Type returns the type: (·) :  a → a → a
func (op ltVVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	return types.NewFunc(a, a, a)
}

// ltVS is a tensor-scalar elementwise less-than.
type ltVS[DT any] struct {
	ltOp[DT]
	binopVS
}

// ltVSRS is a tensor-scalar elementwise less-than.
type ltVSRS[DT any] struct {
	ltOpRS[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op ltVS[DT]) String() string { return "<·" }

// String implements fmt.Stringer.
func (op ltVSRS[DT]) String() string { return "<·" }

// Type returns the type: (·) :  a → b → c
func (op ltVS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a)
	b := hm.TypeVariable('b')               // a
	c := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → a
func (op ltVSRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	b := hm.TypeVariable('b') // b
	return types.NewFunc(a, b, a)
}

// ltSV is a scalar-tensor elementwise less-than.
type ltSV[DT any] struct {
	ltOp[DT]
	binopSV
}

// ltSV is a scalar-tensor elementwise less-than.
type ltSVRS[DT any] struct {
	ltOpRS[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op ltSV[DT]) String() string { return "·<" }

// String implements fmt.Stringer.
func (op ltSVRS[DT]) String() string { return "·<" }

// Type returns the type: (·) :  a → b → c
func (op ltSV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // U
	b := hm.TypeVariable('b')               // (T U) or U
	c := types.MakeDependent(b, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → b
func (op ltSVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // a
	b := hm.TypeVariable('b') // (T b) or b
	return types.NewFunc(a, b, b)
}
