package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	"gorgonia.org/dtype"
	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/tensor"
)

// lteOp is the base op for elementwise less-than-or-equal-to.
type lteOp[DT any] struct{ binop }

type lteOpRS[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op lteOp[DT]) String() string { return "≤" }

// String implements fmt.Stringer.
func (op lteOpRS[DT]) String() string { return "≤" }

func (op lteOp[DT]) do(ctx context.Context, a, b tensor.Basic[DT], prealloc tensor.Basic[bool]) (retVal tensor.Basic[bool], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}

	asSame := fo.AsType == a.Dtype()
	toBroadcast := fo.Broadcast.BroadcastData()

	ord, ok := e.(tensor.Ord[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, ord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for lte")
	}
	switch {
	case toBroadcast:
		err = ord.LteBroadcastable(ctx, a, b, ret, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = ord.Lte(ctx2, a, b, ret, asSame)
	}
	return retVal, err
}

func (op lteOpRS[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc), tensor.As(dtype.Datatype[DT]{}))
	if err != nil {
		return retVal, err
	}

	toBroadcast := fo.Broadcast.BroadcastData()

	ord, ok := e.(tensor.Ord[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, ord, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for lte")
	}
	switch {
	case toBroadcast:
		err = ord.LteBroadcastable(ctx, a, b, ret, true, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = ord.Lte(ctx2, a, b, ret, true)
	}
	return retVal, err
}

// Do performs elementwise less-than-or-equal-to.
func (op lteOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// Do performs elementwise less-than-or-equal-to.
func (op lteOpRS[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise less-than-or-equal-to but with a preallocated return value.
// PreallocDo allows lte to implement ops.PreallocOp.
func (op lteOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[bool], vs ...tensor.Basic[DT]) (retVal tensor.Basic[bool], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// PreallocDo performs elementwise less-than-or-equal-to but with a preallocated return value.
// PreallocDo allows lte to implement ops.PreallocOp.
func (op lteOpRS[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}                                              // DiffWRT returns {false, false} for lte
func (op lteOp[DT]) DiffWRT(inputs int) []bool { return twofalses }

// DiffWRT returns {false, false} for lte
func (op lteOpRS[DT]) DiffWRT(inputs int) []bool { return twofalses }

// lteVV is a tensor-tensor elementwise less-than-or-equal-to.
type lteVV[DT any] struct {
	lteOp[DT]
	binopVV
}

type lteVVRS[DT any] struct {
	lteOpRS[DT]
	binopVV
}

// Type returns the type: (·) (·) :  a → a → b
func (op lteVV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a) or a
	b := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, a, b)
}

// Type returns the type: (·) :  a → a → a
func (op lteVVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	return types.NewFunc(a, a, a)
}

// lteVS is a tensor-scalar elementwise less-than-or-equal-to.
type lteVS[DT any] struct {
	lteOp[DT]
	binopVS
}

// lteVSRS is a tensor-scalar elementwise less-than-or-equal-to.
type lteVSRS[DT any] struct {
	lteOpRS[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op lteVS[DT]) String() string { return "≤·" }

// String implements fmt.Stringer.
func (op lteVSRS[DT]) String() string { return "≤·" }

// Type returns the type: (·) :  a → b → c
func (op lteVS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // (T a)
	b := hm.TypeVariable('b')               // a
	c := types.MakeDependent(a, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → a
func (op lteVSRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T a) or a
	b := hm.TypeVariable('b') // b
	return types.NewFunc(a, b, a)
}

// lteSV is a scalar-tensor elementwise less-than-or-equal-to.
type lteSV[DT any] struct {
	lteOp[DT]
	binopSV
}

// lteSV is a scalar-tensor elementwise less-than-or-equal-to.
type lteSVRS[DT any] struct {
	lteOpRS[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op lteSV[DT]) String() string { return "·≤" }

// String implements fmt.Stringer.
func (op lteSVRS[DT]) String() string { return "·≤" }

// Type returns the type: (·) :  a → b → c
func (op lteSV[DT]) Type() hm.Type {
	a := hm.TypeVariable('a')               // U
	b := hm.TypeVariable('b')               // (T U) or U
	c := types.MakeDependent(b, dtype.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// Type returns the type: (·) : a → b → b
func (op lteSVRS[DT]) Type() hm.Type {
	a := hm.TypeVariable('a') // a
	b := hm.TypeVariable('b') // (T b) or b
	return types.NewFunc(a, b, b)
}
