package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// powOp is the base op for elementwise exponentiation.
type powOp[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op powOp[DT]) String() string { return "^" }

func (op powOp[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, retVal, fo, err := tensor.PrepBasicBinOpCis[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}
	toIncr := fo.Incr
	toBroadcast := fo.Broadcast

	arither, ok := e.(tensor.Arither[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, arither, errors.ThisFn())
	}

	switch {
	case toBroadcast:
		err = arither.PowBroadcastable(ctx, a, b, retVal, newAPA, newAPB, toIncr)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = arither.Pow(ctx2, a, b, retVal, toIncr)
	}
	return retVal, err
}

// Do performs elementwise exponentiation.
func (op powOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise exponentiation but with a preallocated return value.
// PreallocDo allows pow to implement ops.PreallocOp.
func (op powOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// powVV is a tensor-tensor elementwise exponentiation.
type powVV[DT any] struct {
	powOp[DT]
	binopVV
}

// powVS is a tensor-scalar elementwise exponentiation.
type powVS[DT any] struct {
	powOp[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op powVS[DT]) String() string { return "^·" }

// powSV is a scalar-tensor elementwise exponentiation.
type powSV[DT any] struct {
	powOp[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op powSV[DT]) String() string { return "·^" }
