package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// sign is a elementwise sign.
type signOp[DT any] struct{ unop }

// String implements fmt.Stringer.
func (op signOp[DT]) String() string { return "Sign" }

// Do performs elementwise sign.
func (op signOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var signer Signer[DT]
	var ok bool
	if signer, ok = e.(Signer[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, signer, errors.ThisFn())
	}
	if retVal, _, err = handleFuncOpts[DT](e, a, a.Shape()); err != nil {
		return retVal, errors.Wrapf(err, errors.FailedFuncOpt, errors.ThisFn())
	}
	if err = signer.Sign(ctx2, a, retVal); err != nil {
		return retVal, err
	}
	// retVal, err = tensor.Sign(a, tensor.WithContext(ctx2))
	task.End()
	return retVal, err
}

// PreallocDo performs elementwise sign but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op signOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var signer Signer[DT]
	var ok bool
	if signer, ok = e.(Signer[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, signer, errors.ThisFn())
	}
	// TODO check that prealloc has the same shape as expected reetVal shape
	if err = signer.Sign(ctx2, a, prealloc); err != nil {
		return retVal, err
	}
	task.End()
	return prealloc, err
}
