package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// sqrt is a elementwise square root.
type sqrtOp[DT any] struct{ unop }

// String implements fmt.Stringer.
func (op sqrtOp[DT]) String() string { return "√" }

// Do performs elementwise square root.
func (op sqrtOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var squarter Squarter[DT]
	var ok bool
	if squarter, ok = e.(Squarter[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, squarter, errors.ThisFn())
	}
	if retVal, _, err = handleFuncOpts[DT](e, a, a.Shape()); err != nil {
		return retVal, errors.Wrapf(err, errors.FailedFuncOpt, errors.ThisFn())
	}
	if err = squarter.Sqrt(ctx2, a, retVal); err != nil {
		return retVal, err
	}
	// retVal, err = tensor.Sqrt(a, tensor.WithContext(ctx2))
	task.End()
	return retVal, err
}

// PreallocDo performs elementwise square root but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op sqrtOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var squarter Squarter[DT]
	var ok bool
	if squarter, ok = e.(Squarter[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, squarter, errors.ThisFn())
	}
	// TODO check that prealloc has the same shape as expected reetVal shape
	if err = squarter.Sqrt(ctx2, a, prealloc); err != nil {
		return retVal, err
	}
	task.End()
	return prealloc, err
}

// DiffWRT returns {true} for sqrt
func (op sqrtOp[DT]) DiffWRT(inputs int) []bool { return onetrue }
