package stdops

import (
	"context"

	"gorgonia.org/gorgonia/exprgraph"
	"gorgonia.org/gorgonia/internal/datatypes"
	"gorgonia.org/gorgonia/values/dual"
)

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

// DoDiff is the method that allows automatic differentiation of `sub` g.
func (op subOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// DoDiff is the method that allows automatic differentiation of `mul` g.
func (op mulOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// DoDiff is the method that allows automatic differentiation of `div` g.
func (op divOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of pow.
func (op powOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `pow` g.
func (op powOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of sin.
func (op sinOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `sin` g.
func (op sinOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of cos.
func (op cosOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `cos` g.
func (op cosOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of exp.
func (op expOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `exp` g.
func (op expOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of ln.
func (op lnOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `ln` g.
func (op lnOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of log2.
func (op log2Op[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `log2` g.
func (op log2Op[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of neg.
func (op negOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `neg` g.
func (op negOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of square.
func (op squareOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `square` g.
func (op squareOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of sqrt.
func (op sqrtOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `sqrt` g.
func (op sqrtOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of inv.
func (op invOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `inv` g.
func (op invOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of invSqrt.
func (op invSqrtOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `invSqrt` g.
func (op invSqrtOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of log1p.
func (op log1pOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `log1p` g.
func (op log1pOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of expm1.
func (op expm1Op[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `expm1` g.
func (op expm1Op[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of cube.
func (op cubeOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `cube` g.
func (op cubeOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}

// SymDiff performs the symbolic differentiation of tanh.
func (op tanhOp[DT]) SymDiff(g *exprgraph.Graph, inputs []*exprgraph.Node, output *exprgraph.Node, grad *exprgraph.Node) (retVal []*exprgraph.Node, err error) {
	panic("not implemented")
}

// DoDiff is the method that allows automatic differentiation of `tanh` g.
func (op tanhOp[DT]) DoDiff(ctx context.Context, inputs []datatypes.Tensor, output datatypes.Tensor) error {
	adv := exprgraph.T2B[DT](inputs[0]).(*dual.Dual[DT])
	bdv := exprgraph.T2B[DT](inputs[1]).(*dual.Dual[DT])
	cdv := exprgraph.T2B[DT](output).(*dual.Dual[DT])

	advd := adv.Deriv()
	bdvd := bdv.Deriv()

	_, _, _ = cdv, advd, bdvd
	panic("Not implemented")
}
