package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// subOp is the base op for elementwise subtraction.
type subOp[DT any] struct{ binop }

// String implements fmt.Stringer.
func (op subOp[DT]) String() string { return "-" }

func (op subOp[DT]) do(ctx context.Context, a, b, prealloc tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, retVal, fo, err := tensor.PrepBasicBinOpCis[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}
	toIncr := fo.Incr
	toBroadcast := fo.Broadcast

	basicarither, ok := e.(tensor.BasicArither[DT])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, basicarither, errors.ThisFn())
	}

	switch {
	case toBroadcast:
		err = basicarither.SubBroadcastable(ctx, a, b, retVal, newAPA, newAPB, toIncr)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = basicarither.Sub(ctx2, a, b, retVal, toIncr)
	}
	return retVal, err
}

// Do performs elementwise subtraction.
func (op subOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, nil)
}

// PreallocDo performs elementwise subtraction but with a preallocated return value.
// PreallocDo allows sub to implement ops.PreallocOp.
func (op subOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// subVV is a tensor-tensor elementwise subtraction.
type subVV[DT any] struct {
	subOp[DT]
	binopVV
}

// subVS is a tensor-scalar elementwise subtraction.
type subVS[DT any] struct {
	subOp[DT]
	binopVS
}

// String implements fmt.Stringer.
func (op subVS[DT]) String() string { return "-·" }

// subSV is a scalar-tensor elementwise subtraction.
type subSV[DT any] struct {
	subOp[DT]
	binopSV
}

// String implements fmt.Stringer.
func (op subSV[DT]) String() string { return "·-" }
