package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/tensor"
)

// tanh is a elementwise tanh.
type tanhOp[DT any] struct{ unop }

// String implements fmt.Stringer.
func (op tanhOp[DT]) String() string { return "tanh" }

// Do performs elementwise tanh.
func (op tanhOp[DT]) Do(ctx context.Context, vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var tanher Tanher[DT]
	var ok bool
	if tanher, ok = e.(Tanher[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, tanher, errors.ThisFn())
	}
	if retVal, _, err = handleFuncOpts[DT](e, a, a.Shape()); err != nil {
		return retVal, errors.Wrapf(err, errors.FailedFuncOpt, errors.ThisFn())
	}
	if err = tanher.Tanh(ctx2, a, retVal); err != nil {
		return retVal, err
	}
	// retVal, err = tensor.Tanh(a, tensor.WithContext(ctx2))
	task.End()
	return retVal, err
}

// PreallocDo performs elementwise tanh but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op tanhOp[DT]) PreallocDo(ctx context.Context, prealloc tensor.Basic[DT], vs ...tensor.Basic[DT]) (retVal tensor.Basic[DT], err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	ctx2, task := trace.NewTask(ctx, op.String())
	e := tensor.GetEngine(a)
	var tanher Tanher[DT]
	var ok bool
	if tanher, ok = e.(Tanher[DT]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, tanher, errors.ThisFn())
	}
	// TODO check that prealloc has the same shape as expected reetVal shape
	if err = tanher.Tanh(ctx2, a, prealloc); err != nil {
		return retVal, err
	}
	task.End()
	return prealloc, err
}

// DiffWRT returns {true} for tanh
func (op tanhOp[DT]) DiffWRT(inputs int) []bool { return onetrue }
